name: Feature Request
description: Suggest a new feature or enhancement for oh-my-opencode
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        **Please write your issue in English.** See our [Language Policy](https://github.com/code-yeongyu/oh-my-opencode/blob/dev/CONTRIBUTING.md#language-policy) for details.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I will write this issue in English (see our [Language Policy](https://github.com/code-yeongyu/oh-my-opencode/blob/dev/CONTRIBUTING.md#language-policy))
          required: true
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: This feature request is specific to oh-my-opencode (not OpenCode core)
          required: true
        - label: I have read the [documentation](https://github.com/code-yeongyu/oh-my-opencode#readme) or asked an AI coding agent with this project's GitHub URL loaded and couldn't find the answer
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        Describe the problem or limitation you're experiencing...
        Example: "As a user, I find it difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you'd like this feature to work
      placeholder: |
        Describe your proposed solution in detail...
        Example: "Add a new hook that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Describe any alternative solutions you've considered...
        Example: "I tried using X but it didn't work because..."

  - type: textarea
    id: doctor
    attributes:
      label: Doctor Output (Optional)
      description: |
        If relevant to your feature request, run `bunx oh-my-opencode doctor` and paste the output.
        This helps us understand your environment.
      placeholder: |
        Paste the output of: bunx oh-my-opencode doctor
        (Optional for feature requests)
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: |
        Add any other context, screenshots, code examples, or links...
        Examples from other tools/projects are helpful!

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Agent
        - New Hook
        - New Tool
        - New MCP Integration
        - Configuration Option
        - Documentation
        - Other
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation
